management:
    endpoints:
        beans:
            enabled: true
        web:
            expose: "*"
            exposure:
                include: "*"


spring:
    profiles: dev
server:
    port: 8000
---
spring:
    profiles: prod
server:
    port: 80
---
spring:
    profiles: test
server:
    port: 9000
